spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/visitor?serverTimezone=Indian/Mauritius
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/vms
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/vms

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method

api:
  name:/evms

server:
  servlet:
    context-path: /evms