spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/visitor?serverTimezone=Indian/Mauritius
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/visitor?serverTimezone=Indian/Mauritius
    user: admin
    password: password
    baseline-on-migrate: true

jwt:
  secret: REPLACE_THIS_WITH_YOUR_SECRET