spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/visitor?serverTimezone=Indian/Mauritius
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method

api:
  name:/evms

server:
  servlet:
    context-path: /evms