CREATE TABLE users (
  id BIGSERIAL NOT NULL,
  email VARCHAR(100) NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  roles VARCHAR(255) NOT NULL,
  user_name VARCHAR(15) NOT NULL,
  PRIMARY KEY (id)
);