version: '3.9'

services:
  postgres:
    container_name: vms-db
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres/data
volumes:
  db:
    driver: local