version: '3.9'

services:
  postgres:
    container_name: vms-db
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres/data

  keycloak:
    container_name: vms-keycloak
    image: jboss/keycloak:latest
    restart: on-failure
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      DB_PORT: 5432
    ports:
      - '8081:8080'
    depends_on:
      - postgres


volumes:
  db:
    driver: local